version: '2'

services:
  web:
    build: .
    ports:
     - "3072:3072"
    volumes:
     - .:/webapp
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    extra_hosts:
      - "www.habage.com:127.0.0.1"

  redis:
    image: redis:3.2

  mongo:
    image: mongo:3.4.1
